MYSQL_DATABASE_HOST = '127.0.0.1'
MYSQL_DATABASE_PORT = '3306'
MYSQL_DATABASE_DB = 'test_py_db'
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = '123456iou'
DB_URI='mysql+pymysql://{}:{}@{}:{}/{}'.format(MYSQL_DATABASE_USER,MYSQL_DATABASE_PASSWORD, MYSQL_DATABASE_HOST, MYSQL_DATABASE_PORT,MYSQL_DATABASE_DB)
# DB_URI='mysql+pymysql://{}:{}@{}/{}?charset=utf8'.format(MYSQL_DATABASE_USER,MYSQL_DATABASE_PASSWORD, MYSQL_DATABASE_HOST, MYSQL_DATABASE_DB)

print(DB_URI)
SQLALCHEMY_DATABASE_URI=DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

# 郵箱配置
MAIL_SERVER = 'smtp.qq.com'
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = '1058008204@qq.com'
MAIL_DEFAULT_SENDER = '1058008204@qq.com'
MAIL_PASSWORD = 'pkmjyzfjqozdbfdf'
MAIL_PORT = 465

SECRET_KEY = 'CCJ'
DEBUG = True


