"""empty message

Revision ID: 5da48bac621d
Revises: 
Create Date: 2022-08-03 19:49:52.517963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5da48bac621d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_code',
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', mysql.CHAR(length=200), nullable=True),
    mysql_default_charset='utf16',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
