"""empty message

Revision ID: 7204e0a7f43d
Revises: 95611d4cda4a
Create Date: 2022-08-13 00:16:08.126160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7204e0a7f43d'
down_revision = '95611d4cda4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(length=1000), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
