"""empty message

Revision ID: 999ecfbf4bd0
Revises: a1e2ed38f1f6
Create Date: 2022-08-09 09:43:32.283274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999ecfbf4bd0'
down_revision = 'a1e2ed38f1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
