"""empty message

Revision ID: a1e2ed38f1f6
Revises: 1a24f8c51994
Create Date: 2022-08-04 09:12:43.647552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e2ed38f1f6'
down_revision = '1a24f8c51994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_capture', sa.Column('capture', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_capture', 'capture')
    # ### end Alembic commands ###
