"""empty message

Revision ID: d1651518c9b4
Revises: b55cd0b79e69
Create Date: 2022-08-09 11:09:51.748994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1651518c9b4'
down_revision = 'b55cd0b79e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_capture', sa.Column('captcha', sa.String(length=100), nullable=False))
    op.drop_column('email_capture', 'capture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_capture', sa.Column('capture', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('email_capture', 'captcha')
    # ### end Alembic commands ###
